# Generated by Django 5.0 on 2023-12-21 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_userpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.profile'),
        ),
    ]
