# Generated by Django 5.0 on 2023-12-21 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_userpost_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userpost')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.profile')),
            ],
        ),
    ]
