# Generated by Django 5.0 on 2023-12-22 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_comment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000)),
                ('profile_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_from', to='web.profile')),
                ('profile_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_to', to='web.profile')),
            ],
        ),
    ]
